# Generated by Django 6.1.1 on 2026-10-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(unique=True)),
                ('end_time', models.DateTimeField()),
                ('is_booked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
